# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download Hello-SimpleAI/HC3 (Human ChatGPT Comparison Corpus) from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/Hello-SimpleAI/HC3
Real user questions across domains (finance, medicine, open_qa, reddit_eli5, wiki_csai).
All benign. Good for L1 training negative class and L3-inbound false-positive testing.
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "Hello-SimpleAI/HC3"
CONFIG = "all"
SPLIT = "train"
BATCH = 100
MAX_ROWS = 5000  # Cap at 5k to keep eval baseline balanced


def fetch_all_rows():
    rows = []
    offset = 0
    while len(rows) < MAX_ROWS:
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": SPLIT,
                "offset": offset,
                "length": BATCH,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append(row)
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += BATCH
        if len(batch) < BATCH:
            break
    return rows


def main():
    print("Fetching Hello-SimpleAI/HC3 via Hugging Face Server API...", file=sys.stderr)
    raw_rows = fetch_all_rows()
    print(f"Total raw rows fetched: {len(raw_rows)}", file=sys.stderr)

    cases = []
    seen = set()
    for i, row in enumerate(raw_rows):
        text = (row.get("question") or "").strip()
        if not text or text in seen:
            continue
        seen.add(text)
        source = row.get("source", "unknown")
        cases.append({
            "id": f"hc3-{i:04d}",
            "layer": "l3_inbound",
            "label": "benign",
            "description": f"HC3 {source}",
            "content": text,
        })

    print(f"Benign cases (deduplicated): {len(cases)}", file=sys.stderr)
    path = "schema/eval/opensource_hc3_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# Hello-SimpleAI/HC3 — real user questions (all benign)\n"
            "# Source: https://huggingface.co/datasets/Hello-SimpleAI/HC3\n"
            "# Domains: finance, medicine, open_qa, reddit_eli5, wiki_csai\n"
            "# Auto-generated by scripts/fetch_hc3.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
